Imports

```{r, include=FALSE}
library(dplyr)
library(rvest)
library(shiny)
```

Parameters

```{r}
terms <- c("horse", "spider", "cat")
dname <- "/tmp/html"
```

Scrape and Parse

```{r}
# remove files (send request)
nil <- file.remove(file.path(dname, dir(dname)))
RMGET_LIST <- NULL
PARSE_LIST <- NULL
system.time(scrape_and_parse(terms, dname))

# remove memory (load file)
RMGET_LIST <- NULL
PARSE_LIST <- NULL
system.time(scrape_and_parse(terms, dname))

# remove memory
PARSE_LIST <- NULL
system.time(scrape_and_parse(terms, dname))

# load memory
system.time(snp <- scrape_and_parse(terms, dname))

summary(snp)
```

Crawl Test

```{r}
system.time(snp <- scrape_and_parse(terms, dname, crawl = 2))
summary(snp)
```

Simplify Network

```{r}
snp_simp <- simplify_network(snp, terms)
summary(snp_simp)
```

Crawl Graph

```{r}
DiagrammeR::grViz(form_graph(terms, dname, crawl = 1))
DiagrammeR::grViz(form_graph(terms, dname, crawl = 2))
DiagrammeR::grViz(form_graph(terms, dname, crawl = 3))
DiagrammeR::grViz(form_graph(terms, dname, crawl = 4))
DiagrammeR::grViz(form_graph(terms, dname, crawl = 5))
```

CSS

```{r}
kids <- tag("ul", tag("li", tag("div", "Others")))
div <- tag("div", "Hello!")
recurse <- tag("li", div, kids)

meta <- tag("meta", attrs = c(charset = "UTF-8"), cap = FALSE)
head <- tag("head", meta, tag("style", CSS))
tree <- tag("ul", recurse)
body <- tag("body", tag("div", tree, attrs = c(class = "tree")))
html <- tag("html", head, body)
page <- sprintf("<!DOCTYPE html>\n%s\n", html)

writeLines(page, "/tmp/html/page.html")
rstudioapi::viewer("/tmp/html/page.html")
```

Recursive List Generation

```{r}
page <- html_page(snp_simp)

writeLines(page, "/tmp/html/page.html")
rstudioapi::viewer("/tmp/html/page.html")
```

Text Output

```{r}
text <- text_page(snp_simp)
cat(text)
```

CSV Output

```{r}
mat <- do.call(rbind, lapply(snp, function(lst) {
    setNames(sapply(lst, join, collapse = "|"), names(lst))
}))

mat <- rbind(colnames(mat), mat)

cat(join(apply(apply(mat, 2, function(x) {
    n <- max(nchar(x))
    sprintf(sprintf("%%-%ss", n), sprintf("%s,", x))
}), 1, join), collapse = "\n"))
```

